// Generated by CoffeeScript 1.3.3

/*
Postie.js
Copyright 2013 Paul Springett

Version: 0.1.0
Author: Paul Springett
URL: http://github.com/paulspringett/postie.js

Released under the MIT license
http://mit-license.org/
*/


(function() {
  var Postie, root,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __slice = [].slice;

  Postie = {};

  Postie.Client = (function() {

    Client.prototype._callbacks = [];

    function Client(serverUrl) {
      this._receive = __bind(this._receive, this);
      this._listen();
      this.serverUrl = serverUrl;
    }

    Client.prototype.ready = function(callback) {
      var _this = this;
      return this._createFrame(this.serverUrl, function() {
        var uuid;
        uuid = _this._dispatch('getEndpoints', true);
        return _this._registerCallback(uuid, function(methods) {
          _this._createEndpoints(methods);
          return callback();
        });
      });
    };

    Client.prototype._registerCallback = function(uuid, fn) {
      this._callbacks.push({
        uuid: uuid,
        fn: fn
      });
      return [uuid, fn];
    };

    Client.prototype._createFrame = function(serverUrl, callback) {
      var frame;
      frame = document.createElement('iframe');
      frame.setAttribute('src', serverUrl);
      frame.setAttribute('id', 'postie-server-iframe');
      frame.setAttribute('style', 'display:none;');
      frame.onload = callback;
      document.body.appendChild(frame);
      return this._frame = frame.contentWindow;
    };

    Client.prototype._createEndpoints = function(endpoints) {
      var endpoint, _fn, _i, _len,
        _this = this;
      this._endpoints = endpoints;
      _fn = function(endpoint) {
        return _this[endpoint] = function() {
          var args, callback, data, uuid, _ref;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          _ref = this._parseArgs(args), data = _ref[0], callback = _ref[1];
          uuid = this._dispatch(endpoint, data);
          if (callback != null) {
            return this._registerCallback(uuid, callback);
          }
        };
      };
      for (_i = 0, _len = endpoints.length; _i < _len; _i++) {
        endpoint = endpoints[_i];
        _fn(endpoint);
      }
      return this;
    };

    Client.prototype._parseArgs = function(args) {
      var arg;
      if (args.length > 2) {
        throw new Error('ArgumentError: more than 2 args passed to an endpoint. Pass a data argument and a callback argument only');
      }
      if (args.length === 2) {
        return args;
      }
      if (args.length === 1) {
        arg = args[0];
        if (typeof arg === 'function') {
          return [null, arg];
        } else {
          return [arg, null];
        }
      }
      return [null, null];
    };

    Client.prototype._dispatch = function(method, data) {
      var payload, uuid;
      uuid = this._generateUuid();
      payload = this._payload(uuid, method, data);
      this._frame.postMessage(payload, '*');
      return uuid;
    };

    Client.prototype._payload = function(uuid, method, data) {
      var message;
      message = {
        postie: true,
        uuid: uuid,
        method: method,
        payload: data
      };
      return JSON.stringify(message);
    };

    Client.prototype._generateUuid = function() {
      var s4;
      s4 = function() {
        return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
      };
      return "" + (s4()) + (s4()) + "-" + (s4()) + "-" + (s4()) + "-" + (s4()) + "-" + (s4()) + (s4()) + (s4());
    };

    Client.prototype._listen = function() {
      if (window.addEventListener != null) {
        return window.addEventListener('message', this._receive, false);
      } else if (window.attachEvent != null) {
        return window.attachEvent('onmessage', this._receive);
      } else {
        throw new Error('cannot bind to postMessage "message" event on window');
      }
    };

    Client.prototype._receive = function(rawEvent) {
      var callback, event;
      event = new Postie.Event(rawEvent);
      if (!event.isValid) {
        return;
      }
      callback = _.find(this._callbacks, function(cb) {
        return cb.uuid === event.uuid;
      });
      if (callback == null) {
        return;
      }
      callback.fn(event.data);
      return this._callbacks = _.without(this._callbacks, callback);
    };

    return Client;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Postie = Postie;

  Postie.Event = (function() {

    Event.prototype.success = false;

    Event.prototype.isValid = false;

    function Event(event) {
      var message;
      try {
        message = JSON.parse(event.data);
        if (message.postie) {
          this.isValid = true;
        }
        this.uuid = message.uuid;
        this.method = message.method;
        this.data = message.payload;
        this.source = event.source;
      } catch (err) {
        console.log("Failed to parse JSON " + event.data + ", with error: " + err);
        this.isValid = false;
      }
    }

    return Event;

  })();

  Postie.Server = (function() {

    Server.prototype.endpoints = [];

    function Server(options) {
      if (options == null) {
        options = {};
      }
      this.receive = __bind(this.receive, this);

      this.receiver = options.receiver;
      this._listEndpoints(this.receiver);
    }

    Server.prototype.receive = function(rawEvent) {
      var event, sendResponse,
        _this = this;
      event = new Postie.Event(rawEvent);
      if (!event.isValid) {
        return;
      }
      if (event.method === 'getEndpoints') {
        return this.dispatch(event, this.endpoints);
      }
      sendResponse = function(responseData) {
        return _this.dispatch(event, responseData);
      };
      return this.receiver[event.method](event.data, sendResponse);
    };

    Server.prototype.dispatch = function(event, responseData) {
      var frame, payload;
      frame = event.source;
      payload = this.payload(event.uuid, responseData);
      frame.postMessage(payload, '*');
      return event.uuid;
    };

    Server.prototype.payload = function(uuid, data) {
      var message;
      message = {
        postie: true,
        uuid: uuid,
        payload: data
      };
      return JSON.stringify(message);
    };

    Server.prototype.listen = function() {
      if (window.addEventListener != null) {
        return window.addEventListener('message', this.receive, false);
      } else if (window.attachEvent != null) {
        return window.attachEvent('onmessage', this.receive);
      } else {
        throw new Error('cannot bind to postMessage "message" event on window');
      }
    };

    Server.prototype._listEndpoints = function(receiver) {
      var fn, method;
      for (method in receiver) {
        fn = receiver[method];
        this.endpoints.push(method);
      }
      return this.endpoints;
    };

    return Server;

  })();

}).call(this);
